"""add categories and note-category relation

Revision ID: c48e072342ba
Revises: c55bbd9943c6
Create Date: 2026-02-12 05:09:22.858631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48e072342ba'
down_revision: Union[str, None] = 'c55bbd9943c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('note_categories_category_id_fkey', 'note_categories', type_='foreignkey')
    op.drop_constraint('note_categories_note_id_fkey', 'note_categories', type_='foreignkey')
    op.create_foreign_key(None, 'note_categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'note_categories', 'notes', ['note_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('notes_user_id_fkey', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_user_id_fkey', 'notes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'note_categories', type_='foreignkey')
    op.drop_constraint(None, 'note_categories', type_='foreignkey')
    op.create_foreign_key('note_categories_note_id_fkey', 'note_categories', 'notes', ['note_id'], ['id'])
    op.create_foreign_key('note_categories_category_id_fkey', 'note_categories', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
